worker_processes auto;

events {}

http {
server {
	listen 80;
	http2 on;

	server_name internal.ns1010634.ip-40-160-52.us;

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log info;

	# Svelte does its own streaming-to-client, so we don't need to buffer replies
	proxy_buffering off;
	client_body_buffer_size 10m;
	client_max_body_size 100m;

	# Actix microservices do NOT like HTTP 1.0
	proxy_http_version 1.1;
	proxy_set_header Access-Control-Allow-Origin $server_name;

	# API Services
	location /api/auth/ {
		proxy_pass http://ic-auth-svc:8080/;
	}
	location /api/posts/ {
		proxy_pass http://ic-posts-svc:8080/;
	}
	location /api/users/ {
		proxy_pass http://ic-users-svc:8080/;
	}
	location /api/smact/ {
		proxy_pass http://ic-softmod-svc:8080/;
	}
}
}
