-- IC_UDB_USER is the user for the Auth Microservice

GRANT USAGE ON SCHEMA UserDB TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION UserDB.GetAccountId TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION UserDB.GetAccountData TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION UserDB.GetAccountPreferences TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION UserDB.CreateAccount TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION UserDB.IsUsernameFree TO IC_UDB_USER;

GRANT USAGE ON SCHEMA Legal TO IC_UDB_USER;
GRANT EXECUTE ON FUNCTION Legal.IsAgeNeededOnSignup TO IC_UDB_USER;


-- Users Microservice
GRANT USAGE ON SCHEMA UsersSvc TO IC_USERS_SVC_USER;
GRANT EXECUTE ON FUNCTION UsersSvc.GetUserBadges TO IC_USERS_SVC_USER;