# === File Locations ===
hba_file = '/etc/postgresql/pg_hba.conf'

# === Connections & Authentication ===
# Required for containers (default: none)
listen_addresses = '*'
# We run ALL containers on 8080 internally (default: 5432)
port = 8080
# This is a local-dev server, not prod (default: 100)
max_connections = 25
# No connections are manual users (default: 1min)
authentication_timeout = 5s
password_encryption = scram-sha-256

# === Resource Consumption ===
# Better performance, and we control the OS (default: try)
huge_pages = try
# Make sure it's off. We don't use it. (default: 0)
max_prepared_transactions = 0

# === Client Connection Details ===
# This is a local-dev server, not prod (default: NOTICE)
client_min_messages = DEBUG1
# default: true
check_function_bodies = false
# We don't need to allow slop when we design everything properly (default: 0)
statement_timeout = 10s
# YMD is the only format that eliminates all ambiguity (default: ISO, MDY)
DateStyle = 'ISO, YMD'
# Any timezone logic is left up to the FE/browser to do local conversions (default: UTC)
TimeZone = UTC

# === Version and platform comatibility ===
# Doesn't provide actual security, but a reminder that containerized systems should be static (default: on)
allow_alter_system = off