-- CREATE TABLE IF NOT EXISTS UserDB.Account (
-- 	id
-- 		BIGINT NOT NULL,
-- 	date_created
-- 		TIMESTAMP NOT NULL
-- 		DEFAULT CURRENT_TIMESTAMP,
-- 	is_login_allowed BOOL NOT NULL
-- 		DEFAULT 1,
-- 
-- 	pass_hash
-- 		BINARY(128) NOT NULL,
-- 	pass_salt
-- 		BINARY(16) NOT NULL,
-- 	username
-- 		VARCHAR(50) NOT NULL,
-- 	email
-- 		VARCHAR(255) NOT NULL,
-- 
-- 	location
-- 		CHAR(2) NOT NULL,
-- 	age_category
-- 		TINYINT NOT NULL,
-- 	content_level
-- 		TINYINT NOT NULL,
-- 
-- 	PRIMARY KEY(id),
-- 	UNIQUE KEY(username),
-- 	UNIQUE KEY(email),
-- 	INDEX(username(20)),
-- 	INDEX(email(20))
-- );

-- Just index the first 20 characters to preserve space
-- TODO: Once we get some users, we can run some performance metrics
-- create or replace index IX_Account_username
-- 	ON UserDB.Account(username(20));
-- create or replace index IX_Account_email
-- 	ON UserDB.Account(email(20));


-- CREATE TABLE IF NOT EXISTS UserDB.Claim (
-- 	id
-- 		INT UNSIGNED NOT NULL
-- 		AUTO_INCREMENT,
-- 	name
-- 		VARCHAR(20) NOT NULL,
-- 	description
-- 		TINYTEXT NOT NULL,
-- 
-- 	PRIMARY KEY(id),
-- 	UNIQUE KEY(name)
-- );

-- NOTE: None of this stuff is implemented yet
-- INSERT INTO UserDB.Claim(name, description) VALUES
-- 	('is_unverified', 'The email is unverified, strictly limiting what they can do'),
-- 	('is_post_banned', 'Temporary ban on posting'),
-- 	('is_comment_banned', 'Temporary ban on commenting'),
-- 	('optin_news', 'User can see news & current events'),
-- 	('optin_politics', 'User can see political content'),
-- 	('mod_add_tags', 'Can add tags to a post'),
-- 	('mod_set_content_lvl', 'Can update a posts content level'),
-- 	('mod_ban_user', 'Can ban users');


-- CREATE TABLE IF NOT EXISTS UserDB.AccountClaim (
-- 	account_id
-- 		INT UNSIGNED NOT NULL
-- 		REFERENCES UserDB.Account(id),
-- 	claim_id
-- 		INT UNSIGNED NOT NULL
-- 		REFERENCES UserDB.Claim(id),
-- 
-- 	UNIQUE KEY(account_id, claim_id),
-- 	INDEX(account_id)
-- );
